name: Deploy to ECR Repository

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    name: Deploy Docker image to ECR
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: 코드 Checkout
        uses: actions/checkout@v4

      - name: AWS Credentials 가져오기
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: AWS ECR 로그인
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: 스크래퍼 도커 이미지 생성 및 배포
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # 도커 이미지 생성
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

          # ECR로 도커 이미지 PUSH
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
